services:
  app:
    build:
      context: ./.devcontainer
      dockerfile: dockerfile.devcontainer
      args:
        USER: ${USER_NAME}
        UID: ${UID}
    tty: true
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - ${HOME}/.codex:/home/${USER_NAME}/.codex
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  db:
    image: postgres:17.6-bookworm
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-app}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
